version: '3.8'

services:
  db:
    build: sql/.
    image: diavgeia-db:latest
    container_name: diavgeia-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5431:5432"

volumes:
  pgdata:
