version: '3.8'

services:
  api:
    build: api/.
    image: diavgeia-api:latest
    container_name: diavgeia-api
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "${API_PORT}:3000"
  db:
    build: db/.
    image: diavgeia-db:latest
    container_name: diavgeia-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"

volumes:
  pgdata:
